### ISSUE TITLE
Add Ideas to WIKI (supertemporal, paratemporal, peritemporal)........

### ISSUE THREAD

**Issue by christoph-v** [christoph-v/spark#8]
Christoph, I had some ideas like supertemporal (like superposition, but in time), paratemporal and peritemporal.  I am not sure if you can include these in your ideas.

 

John

**Comment by coderextreme** [comment]
I am not sure how to add pages, edit, etc.   I need a basic tutorial on wiki editing.

**Comment by christoph-v** [comment]
Hi John.
Do you have TeamViewer or similar? I can show you. I have got time now.

KR

**Comment by christoph-v** [comment]
ill send you a private mail

**Comment by coderextreme** [comment]
I may have figured it out but I’m not a collaborator on the wiki? Thanks, Add me as yottzumm@gmail.com on skype and yottzumm#9156 on discord.  Others are available. John Sent from Mail for Windows 10 From: Christoph VALENTINSent: Sunday, December 27, 2020 8:37 PMTo: christoph-v/sparkCc: John Carlson; CommentSubject: Re: [christoph-v/spark] Add Ideas to WIKI (supertemporal, paratemporal, peritemporal)........ (#8) Hi John.Do you have TeamViewer or similar? I can show you. I have got time now.KR—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by christoph-v** [comment]
OK, have invited you as Skype contact

**Comment by coderextreme** [comment]
I haven’t seen your invite yet.  Will try to add you. John Sent from Mail for Windows 10 From: Christoph VALENTINSent: Sunday, December 27, 2020 8:54 PMTo: christoph-v/sparkCc: John Carlson; CommentSubject: Re: [christoph-v/spark] Add Ideas to WIKI (supertemporal, paratemporal, peritemporal)........ (#8) OK, have invited you as Skype contact—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by coderextreme** [comment]
There are a lot of Christoph’s  I will search by your email. John Sent from Mail for Windows 10 From: John CarlsonSent: Sunday, December 27, 2020 8:58 PMTo: christoph-v/spark; christoph-v/sparkCc: CommentSubject: RE: [christoph-v/spark] Add Ideas to WIKI (supertemporal, paratemporal, peritemporal)........ (#8) I haven’t seen your invite yet.  Will try to add you. John Sent from Mail for Windows 10 From: Christoph VALENTINSent: Sunday, December 27, 2020 8:54 PMTo: christoph-v/sparkCc: John Carlson; CommentSubject: Re: [christoph-v/spark] Add Ideas to WIKI (supertemporal, paratemporal, peritemporal)........ (#8) OK, have invited you as Skype contact—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by coderextreme** [comment]
Added at:  https://github.com/christoph-v/spark/wiki/Temporal-Positioning

Also linked under Draft-Ideas.md (needs work, leaving issue open).

**Comment by coderextreme** [comment]
Suggestion that we have both Spatial Positioning and Temporal Positioning, or some combination

**Comment by christoph-v** [comment]
> Suggestion that we have both Spatial Positioning and Temporal Positioning, or some combination

I am thinking, too. Probably we should merge both on one page.

Probably we should move it to digits repository/wiki

Kr
